### ISSUE TITLE
Broken twitter link

### ISSUE THREAD

**Issue by Njong392** [Kanyelings/mentormatch-ng#47]
Twitter link takes me to instagram page instead, and the page error says it's broken.

**Comment by elroykanye** [comment]
Could you show this with a photo?

**Comment by elroykanye** [comment]
Never mind

**Comment by elroykanye** [comment]
I just found out what the issue is.
The base domain I set for twitter was the same for Instagram 😄
Good thing I even used that method. Easy error to spot.

You'll find the file at `src/app/models/entity/developer.ts` in [this repo](github.com/elroykanye/mentormatch-ng) where you have the `private static getCompleteSocialLinks` method (line 29).

**Comment by elroykanye** [comment]
I have fixed it t
